### PR TITLE
Adding MCA Assessment Results Data Mapping Matrix

### PR DESCRIPTION
**Pull request by davidreeg**
Current draft - working on documentation corrections per feedback from Pearson.

### CODE REVIEW

**Comment by davidreeg** [comment]
@mmdolbow @steve-dlp Pearson provided a bunch of feedback today regarding inconsistencies between this document and Swagger, as well as inconsistencies between this revision and other revisions of this mapping matrix which are floating around.  My intention is to work with Pearson to clean up this mapping matrix so that it is an accurate reflection of the current MCA/Alt-MCA Assessment Results implementation.

**Comment by mmdolbow** [comment]
OK, I will review as best as I can. At first glance right away I'd prefer to move descriptor tables out of this matrix and into separate CSV files like I do elsewhere. If we need to mark them somehow as "only used by assessment vendors", we can do that. But I too am out of my depth with reviewing the basic elements.

Speaking of Swagger, which sandbox or staging site should be our source of reference? 22-23 staging?

**Comment by davidreeg** [comment]
@mmdolbow, I completely agree with moving the descriptors out of this matrix and into CSV files like you do elsewhere.  Just like what happened last month, vendors may try to load Assessment descriptor values even though they aren't (and aren't supposed to) implement the Assessment API resources.  I think we should treat all descriptors the same way regardless of which data domain(s) they are used. 

The latest revision of the Assessment API is in the Staging v5 environment.  The Assessment API in all the other environments is (as far as I know) still out of date. @steve-dlp and I discussed last week plans for updating the Assessment API in the other environments, but the timeline for that is still TBD.  We do, however, expect that the Assessment API is needed in production by the end of May to satisfy MDE's schedule for this pilot.

**Comment by davidreeg** [comment]
@mmdolbow @steve-dlp, Please wait on spending any time on your review.  I'm working on a whole new revision of the Data Elements matrix, reorganized by Ed-Fi entity based on the sample JSON that Double Line provided.

@mmdolbow, How soon do you think you could have these assessment descriptors converted to CSV like the other descriptors?  The next project meeting with Pearson is scheduled for Friday March 31st at 10AM, and my goal is to have my new revision of the Data Elements matrix done by Thursday.
Thank you!

**Comment by mmdolbow** [comment]
> @mmdolbow, How soon do you think you could have these assessment descriptors converted to CSV like the other descriptors? The next project meeting with Pearson is scheduled for Friday March 31st at 10AM, and my goal is to have my new revision of the Data Elements matrix done by Thursday. Thank you!

I've set aside time to get those exported tomorrow. I will place them in the normal descriptor table folder according to your note to the various stakeholders today, making adjustments to the markdown docs as necessary. (For example I'll list sources for the Assessment Descriptors as staging 22-23, which is different than the other descriptors.)

**Comment by mmdolbow** [comment]
I just exported 10 custom descriptor tables for assessments, all [linked here](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/blob/master/descriptorTables/AboutDescriptorTables.md#assessment-descriptors). Some notes about these descriptor table exports:

- We already have several of these exported, like the following (with details). Just because a descriptor has more than the records in the draft matrix, doesn't mean Pearson needs to USE more than those. Should we indicate somehow which ones they should limit themselves to? Here are the ones I'm talking about:
  -  [Academic Subject Descriptor](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/blob/master/descriptorTables/AcademicSubjectDescriptor.csv) has more than M, R, and S. 
  - [Grade Level Descriptor](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/blob/master/descriptorTables/GradeLevelDescriptor.csv) has more than the core 1-12 grades
- Some descriptors exist in both the 'access' and 'mcamtas' namespaces. Since @davidreeg only listed the latter in his initial mapping matrix, that's what I'll limit these exports to for now - but it would be relatively easy to do both. (And we should note to Pearson that there is a 'folder' in the path so they can't just pull ALL the descriptors if they want theirs to match.) Those are:
  - Accommodation
  - Assessment Format
  - Assessment Reporting Method
  - Performance Level
- I noticed GeneralEnrollmentDescriptor have three values without a 'folder' name; ~~even if Pearson only needs the one record in the 'mcamtas' namespace, should we export them all?~~ I exported them all on advice of the folks from Pearson.

**Comment by mmdolbow** [comment]
@davidreeg a few other things I recommend for the main "Data Elements" tab:
- Format as table so that sorting and filtering can be accomplished more easily
- Don't use color for meaning; add another column for the designation of the colors if necessary
-  Clean up extra data in columns L, M, N - remove if not needed, integrate into the table if they are needed

And once you're good with the desciptor exports, we can just have a "custom descriptors" tab that lists they descriptors they need to be aware of, and links to where to find them

**Comment by mmdolbow** [comment]
@davidreeg I was briefly in a meeting today with Pearson and they indicated that they definitely expected the full four values for General Enrollment Desctriptor, so I exported them all into [the CSV](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/blob/master/descriptorTables/GeneralEnrollmentDescriptor.csv) via [this commit](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/commit/0335480155cad746e088c6c394093e558206851e)

**Comment by davidreeg** [comment]
@mmdolbow, Thanks for adding the assessment descriptor tables in GitHub.  Note that there are a couple of issues currently with the assessment descriptors that I have asked @steve-dlp to address:

1. AttemptLogicMetDescriptor currently has the namespace "AttemptLogicDescriptor" so that's how it currently shows up in the MDE-EdFi-Documentation descriptorTables list.  I've asked DoubleLine to fix the namespace for the AttemptLogicMetDescriptor.
2. AssessmentReportingMethodDescriptor currently has the namespace with a lowercase "a", so in the MDE-EdFi-Documentatior descriptorTables list it currently shows up at the bottom of the list since the sort order doesn't ignore case. I've asked Double Line to fix the namespace for AssesmentReportingMethodDescriptor to make the first lettter of the descriptor name uppercase per convention.

**Comment by mmdolbow** [comment]
> @mmdolbow, Thanks for adding the assessment descriptor tables in GitHub. Note that there are a couple of issues currently with the assessment descriptors that I have asked @steve-dlp to address:
> 
>     1. AttemptLogicMetDescriptor currently has the namespace "AttemptLogicDescriptor" so that's how it currently shows up in the MDE-EdFi-Documentation descriptorTables list.  I've asked DoubleLine to fix the namespace for the AttemptLogicMetDescriptor.
> 
>     2. AssessmentReportingMethodDescriptor currently has the namespace with a lowercase "a", so in the MDE-EdFi-Documentatior descriptorTables list it currently shows up at the bottom of the list since the sort order doesn't ignore case. I've asked Double Line to fix the namespace for AssesmentReportingMethodDescriptor to make the first lettter of the descriptor name uppercase per convention.

I saw those notes, which is why I added them to this [section](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/blob/master/descriptorTables/AboutDescriptorTables.md#assessment-descriptors) of the markdown file. The way I figure it, this reflects the current database reality. Once those changes are made, I'll re-run the exports and update the documentation accordingly.

**Comment by davidreeg** [comment]
@mmdolbow, the Assessment descriptor namespace changes for AttemptLogicMetDescriptor and AssessmentReportingMethodDescriptor  were both deployed to the Ed-FI v5 Staging environment today.  Could you please regenerate the descriptorTables documentation in GitHub for those two descriptors? Thank you!

**Comment by mmdolbow** [comment]
> @mmdolbow, the Assessment descriptor namespace changes for AttemptLogicMetDescriptor and AssessmentReportingMethodDescriptor were both deployed to the Ed-FI v5 Staging environment today. Could you please regenerate the descriptorTables documentation in GitHub for those two descriptors? Thank you!

Done via [this commit](https://github.com/mn-mde-edfi/MDE-EdFi-Documentation/commit/e9f22d9f4abfa4c22b37b7ac3eccb931fc796461) and a subsequent fix to force the case change.

**Comment by davidreeg** [comment]
Per today's discussion with @mmdolbow, closing this pull request without merging to master branch.

**Pull request closed without merging**
